version: '3.7'

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: unbox-assignment-loki-1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki-data:/loki-data
      - ./loki-wal:/wal   # ✅ Add this line
    command: -config.file=/etc/loki/loki-config.yaml


  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/var/log/robot
      - ./positions.yaml:/tmp/positions.yaml

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
