name: Deploy Grafana Stack

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Docker and Compose
      run: |
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Run Docker Compose
      run: docker compose -f docker-compose.yml up -d --build
